
$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: ../../src/ml_training # Path to training code RELATIVE to this YAML
command: >-
  python train_condition.py 
  --data ${{inputs.training_data}}        
inputs:
  training_data:
    type: uri_folder

    path: azureml://subscriptions/92cb0224-ba4d-47f9-8489-37d2045c0dd0/resourcegroups/demo_tyremlops_poc_sind/workspaces/demo_tyrehealth_poc/datastores/datastore_adls_gen2_tyrepoc/paths/raw/condition/
environment: azureml:tyre-train-env-cpu@latest 
compute: azureml:tyre-health-train    
display_name: Train_Condition_Model_ResNet18
experiment_name: Tyre_Model_condition 
