
$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: ../../src/ml_training # Path to training code RELATIVE to this YAML
command: >-
  python train.py 
  --task pressure
  --data ${{inputs.training_data}}
  --epochs 15                 
  --batch_size 32
  --learning_rate 1e-3        
  --weight_decay 1e-4
  --patience 4
  --dropout 0                 
  --num_workers 4
  --k_folds 5                 
inputs:
  training_data:
    type: uri_folder
    path: azureml://subscriptions/92cb0224-ba4d-47f9-8489-37d2045c0dd0/resourcegroups/demo_tyremlops_poc_sind/workspaces/demo_tyrehealth_poc/datastores/datastore_adls_gen2_tyrepoc/paths/raw/pressure/
environment: azureml:tyre-train-env-cpu@latest
compute: azureml:tyre-health-train
display_name: Train_Pressure_Model_ResNet18_KFold
experiment_name: Tyre_Model_pressure 