
$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: ../../src/ml_training # Path to training code RELATIVE to this YAML
command: >-
  python train.py 
  --task condition
  --data ${{inputs.training_data}}
  --epochs 15                 
  --batch_size 32
  --learning_rate_head 5e-4
  --learning_rate_body 1e-6
  --weight_decay 1e-4
  --patience 4
  --dropout 0.5               
  --num_workers 4
  # --k_folds 0               
inputs:
  training_data:
    type: uri_folder

    path: azureml://subscriptions/92cb0224-ba4d-47f9-8489-37d2045c0dd0/resourcegroups/demo_tyremlops_poc_sind/workspaces/demo_tyrehealth_poc/datastores/tyre_health_poc_data/paths/tyrepocdata/raw/condition/
environment: azureml:tyre-train-env-cpu@latest 
compute: azureml:tyre-health-build    
display_name: Train_Condition_Model_ResNet18
experiment_name: Tyre_Model_condition 
