# aml/environment/environment.yaml
$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: tyre-train-env-cpu # Give it a distinct name
version: 1 
description: CPU-only environment for Tyre Health training (Python 3.11)
# Use a more generic base image for Ubuntu 22.04
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04 
conda_file: conda_cpu.yaml # Point to a new CPU-specific conda file