# aml/environment/environment.yml
$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: tyre-train-env   # Name used to reference in jobs
version: 1             # Increment if conda.yaml changes
description: Environment for Tyre Health training (ResNet18, PyTorch CUDA).
conda_file: conda.yaml # Path relative to THIS file
image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda12.1-cudnn8-ubuntu22.04 # Specific base image